"""Per-conversation media library — Audio/Video Phase 3.

Tracks media files (captured screen recordings, dropped audio/video/image)
that belong to a specific conversation's video editing session. The library
is a list of REFERENCES, not a file store: deleting an entry removes it
from the conversation but does NOT delete the source file (per design Item B
"Media library = per-conversation list of references, not a per-conversation
file store").

Storage
-------
* ``~/ora/sessions/<conversation_id>/media-library.json`` — list of entries
* ``~/ora/sessions/<conversation_id>/thumbnails/<entry_id>.jpg`` — single
  representative frame for video entries (generated by FFmpeg on add)

Entry shape::

    {
      "id": "<12-char hex>",
      "added_at": "ISO 8601",
      "source_path": "<absolute path>",
      "display_name": "<user-visible name>",
      "kind": "video" | "audio" | "image",
      "mime": "video/mp4",
      "size_bytes": 12345,
      "duration_ms": 1234,           # video / audio only; null for images
      "width": 1920,                 # video / image only
      "height": 1080,
      "thumbnail_path": "<abs path>" # video only
    }

Public API
----------
``MediaLibrary(conversation_id)``       — instantiate for a conversation
``library.add_entry(source_path, **)``  — register a file; generates thumb
``library.list_entries()``              — current entries
``library.rename(entry_id, new_name)``
``library.remove(entry_id)``            — removes from library (and thumb)
``library.get_entry(entry_id)``
``library.get_thumbnail_path(entry_id)``
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import threading
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

WORKSPACE_ROOT = Path(os.path.expanduser("~/ora")).resolve()
SESSIONS_ROOT = WORKSPACE_ROOT / "sessions"
FFMPEG_BINARY = shutil.which("ffmpeg") or "/opt/homebrew/bin/ffmpeg"
FFPROBE_BINARY = shutil.which("ffprobe") or "/opt/homebrew/bin/ffprobe"

VIDEO_EXTS = {".mp4", ".mov", ".m4v", ".avi", ".mkv", ".webm"}
AUDIO_EXTS = {".mp3", ".m4a", ".wav", ".flac", ".ogg", ".aac"}
IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".svg", ".gif"}


def _classify(path: Path) -> str:
    ext = path.suffix.lower()
    if ext in VIDEO_EXTS:
        return "video"
    if ext in AUDIO_EXTS:
        return "audio"
    if ext in IMAGE_EXTS:
        return "image"
    return "other"


def _probe_metadata(path: Path) -> dict:
    """Return ``{duration_ms, width, height, mime}`` for a file using ffprobe."""
    try:
        result = subprocess.run(
            [
                FFPROBE_BINARY,
                "-v", "error",
                "-show_entries",
                "format=duration:stream=width,height,codec_type",
                "-of", "json",
                str(path),
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=20,
        )
        data = json.loads(result.stdout or b"{}")
    except Exception:
        return {}
    out: dict = {}
    fmt = data.get("format", {}) or {}
    if fmt.get("duration"):
        try:
            out["duration_ms"] = int(float(fmt["duration"]) * 1000)
        except (ValueError, TypeError):
            pass
    for stream in data.get("streams", []) or []:
        if stream.get("codec_type") == "video":
            if stream.get("width"):
                out["width"] = int(stream["width"])
            if stream.get("height"):
                out["height"] = int(stream["height"])
            break
    return out


def _generate_thumbnail(source: Path, target: Path, kind: str) -> bool:
    """Generate a single-frame thumbnail JPEG for video files.

    Returns True on success. Image files reuse the source directly (no
    thumbnail needed). Audio files don't get a generated thumbnail in
    Phase 3 — the UI uses a generic glyph.
    """
    target.parent.mkdir(parents=True, exist_ok=True)
    if kind == "image":
        return False  # UI uses the source directly via /api/media-library/<id>/preview
    if kind != "video":
        return False
    # Grab the frame at 1 second in (or 0 if shorter), scaled to 320 px wide.
    argv = [
        FFMPEG_BINARY,
        "-hide_banner",
        "-loglevel", "error",
        "-y",
        "-ss", "1",
        "-i", str(source),
        "-frames:v", "1",
        "-vf", "scale=320:-2",
        "-q:v", "5",
        str(target),
    ]
    try:
        result = subprocess.run(argv, stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE, timeout=20)
    except Exception:
        return False
    if result.returncode != 0 or not target.exists() or target.stat().st_size == 0:
        # Try with -ss 0 in case the source is shorter than 1 second.
        argv2 = list(argv)
        idx = argv2.index("-ss")
        argv2[idx + 1] = "0"
        try:
            r2 = subprocess.run(argv2, stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE, timeout=20)
        except Exception:
            return False
        return r2.returncode == 0 and target.exists() and target.stat().st_size > 0
    return True


def _slugify_for_display(s: str) -> str:
    s = re.sub(r"\s+", " ", s or "").strip()
    return s[:120]


# ── MediaLibrary ──────────────────────────────────────────────────────────────

class MediaLibrary:
    """Per-conversation media reference list.

    Construct with a conversation_id. State is loaded from disk on init
    and persisted on every mutation. Thread-safe via a per-instance lock.
    """

    def __init__(self, conversation_id: str) -> None:
        self.conversation_id = conversation_id
        self._lock = threading.Lock()
        self.session_dir = SESSIONS_ROOT / conversation_id
        self.session_dir.mkdir(parents=True, exist_ok=True)
        self.state_path = self.session_dir / "media-library.json"
        self.thumbnails_dir = self.session_dir / "thumbnails"
        self._entries: list[dict] = []
        self._load()

    # ── persistence ─────────────────────────────────────────────────────────

    def _load(self) -> None:
        if not self.state_path.exists():
            self._entries = []
            return
        try:
            data = json.loads(self.state_path.read_text(encoding="utf-8"))
            self._entries = list(data.get("entries", []))
        except Exception:
            # Corrupt state — start fresh but keep the broken file as a sidecar.
            backup = self.state_path.with_suffix(".json.broken")
            try:
                self.state_path.replace(backup)
            except Exception:
                pass
            self._entries = []

    def _save(self) -> None:
        payload = {
            "conversation_id": self.conversation_id,
            "schema_version": 1,
            "entries": self._entries,
        }
        # Atomic-ish write: tmp + replace.
        tmp = self.state_path.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        tmp.replace(self.state_path)

    # ── public surface ─────────────────────────────────────────────────────

    def list_entries(self) -> list[dict]:
        with self._lock:
            return list(self._entries)

    def get_entry(self, entry_id: str) -> dict | None:
        with self._lock:
            for e in self._entries:
                if e.get("id") == entry_id:
                    return dict(e)
        return None

    def add_entry(
        self,
        source_path: str | Path,
        display_name: str | None = None,
        mime: str | None = None,
    ) -> dict:
        src = Path(source_path)
        if not src.exists():
            raise FileNotFoundError(f"source not found: {src}")
        kind = _classify(src)

        meta = _probe_metadata(src) if kind in ("video", "audio", "image") else {}
        entry_id = uuid.uuid4().hex[:12]
        thumb = self.thumbnails_dir / f"{entry_id}.jpg"
        thumb_made = _generate_thumbnail(src, thumb, kind)

        entry = {
            "id": entry_id,
            "added_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "source_path": str(src.resolve()),
            "display_name": _slugify_for_display(display_name or src.name),
            "kind": kind,
            "mime": mime or "",
            "size_bytes": src.stat().st_size,
            "duration_ms": meta.get("duration_ms"),
            "width": meta.get("width"),
            "height": meta.get("height"),
            "thumbnail_path": str(thumb) if thumb_made else None,
        }
        with self._lock:
            self._entries.append(entry)
            self._save()
        return dict(entry)

    def rename(self, entry_id: str, new_name: str) -> dict | None:
        clean = _slugify_for_display(new_name)
        if not clean:
            raise ValueError("new_name cannot be empty")
        with self._lock:
            for e in self._entries:
                if e.get("id") == entry_id:
                    e["display_name"] = clean
                    self._save()
                    return dict(e)
        return None

    def remove(self, entry_id: str) -> bool:
        """Remove the library entry. Does NOT delete the source file."""
        with self._lock:
            new_entries = []
            removed = None
            for e in self._entries:
                if e.get("id") == entry_id:
                    removed = e
                    continue
                new_entries.append(e)
            if removed is None:
                return False
            self._entries = new_entries
            self._save()
        # Outside the lock: clean up the thumbnail file. Failure is non-fatal
        # (a stray thumbnail just wastes a few KB of disk).
        thumb = removed.get("thumbnail_path")
        if thumb:
            try:
                Path(thumb).unlink()
            except FileNotFoundError:
                pass
            except Exception:
                pass
        return True

    def get_thumbnail_path(self, entry_id: str) -> Path | None:
        e = self.get_entry(entry_id)
        if not e:
            return None
        thumb = e.get("thumbnail_path")
        if not thumb:
            return None
        p = Path(thumb)
        return p if p.exists() else None


# ── Module-level cache (one MediaLibrary per conversation_id) ────────────────

_libraries: dict[str, MediaLibrary] = {}
_libraries_lock = threading.Lock()


def get_library(conversation_id: str) -> MediaLibrary:
    """Return the (cached) MediaLibrary for a conversation, creating on demand."""
    if not conversation_id:
        raise ValueError("conversation_id required")
    with _libraries_lock:
        lib = _libraries.get(conversation_id)
        if lib is None:
            lib = MediaLibrary(conversation_id)
            _libraries[conversation_id] = lib
        return lib


__all__ = [
    "MediaLibrary",
    "get_library",
    "VIDEO_EXTS",
    "AUDIO_EXTS",
    "IMAGE_EXTS",
]
