"""Workflow spec parser — parses workflow specifications into structured fields.

A workflow spec is a markdown file with YAML frontmatter generated by
Framework — Corpus Formalization C-Design (per PFF-CFF-OFF Integration
Architecture). It indexes a coherent multi-framework workflow: which PFFs
write to the corpus, which OFFs read from it, the chain relationships, and
(when extended by Framework — Oversight Configuration) the cross-corpus
oversight rules.

Author: meta-layer implementation per Reference — Meta-Layer Architecture §13.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Optional

try:
    import yaml
except ImportError:
    yaml = None


# ---------- Data classes ----------

@dataclass
class PFFEntry:
    name: str
    path: str = ""
    writes_to_section: str = ""


@dataclass
class OFFEntry:
    name: str
    path: str = ""
    reads_from_sections: list = field(default_factory=list)


@dataclass
class ChainPropagationRule:
    source: str
    dependent: str
    action: str  # "re_validate", "re_instantiate", "no_op"
    condition: str  # "section_updated", "instance_recreated", "template_version_changed"


@dataclass
class OFFDependencyRule:
    off_id: str
    sections_required: list = field(default_factory=list)
    stale_threshold_days: int = 0


@dataclass
class CadenceCoordination:
    sequence: list = field(default_factory=list)
    reason: str = ""


@dataclass
class WorkflowOversightRules:
    chain_propagation_rules: list = field(default_factory=list)
    off_dependency_rules: list = field(default_factory=list)
    cadence_coordination: list = field(default_factory=list)
    escalation_overrides: dict = field(default_factory=dict)


@dataclass
class ParsedWorkflowSpec:
    file_path: str
    frontmatter: dict = field(default_factory=dict)
    workflow_id: str = ""
    workflow_name: str = ""
    owner: str = ""
    corpus_template_path: str = ""
    corpus_instance_directory: str = ""
    pffs: list = field(default_factory=list)  # list[PFFEntry]
    offs: list = field(default_factory=list)  # list[OFFEntry]
    chain_relationships: list = field(default_factory=list)  # raw chain entries
    oversight: Optional[WorkflowOversightRules] = None
    body: str = ""


# ---------- Public API ----------

def parse_workflow_spec_file(path: str) -> ParsedWorkflowSpec:
    """Parse a workflow spec from a markdown file."""
    with open(path, encoding="utf-8") as f:
        content = f.read()
    return parse_workflow_spec_text(content, file_path=path)


def parse_workflow_spec_text(content: str, file_path: str = "") -> ParsedWorkflowSpec:
    """Parse workflow spec content from a string."""
    spec = ParsedWorkflowSpec(file_path=file_path)

    fm, body = _split_frontmatter(content)
    spec.body = body

    if not fm or yaml is None:
        return spec

    try:
        fm_data = yaml.safe_load(fm) or {}
    except yaml.YAMLError:
        return spec

    spec.frontmatter = fm_data

    # Top-level fields
    spec.workflow_id = str(fm_data.get("workflow_id", fm_data.get("workflow", "")))
    spec.workflow_name = str(fm_data.get("workflow", spec.workflow_id))
    spec.owner = str(fm_data.get("owner", ""))
    spec.corpus_template_path = str(fm_data.get("corpus_template", ""))
    spec.corpus_instance_directory = str(fm_data.get("corpus_instance_directory", ""))

    # PFFs
    for p in fm_data.get("pffs", []) or []:
        if isinstance(p, dict):
            spec.pffs.append(PFFEntry(
                name=str(p.get("name", "")),
                path=str(p.get("path", "")),
                writes_to_section=str(p.get("writes_to_section", "")),
            ))

    # OFFs
    for o in fm_data.get("offs", []) or []:
        if isinstance(o, dict):
            spec.offs.append(OFFEntry(
                name=str(o.get("name", "")),
                path=str(o.get("path", "")),
                reads_from_sections=list(o.get("reads_from_sections", []) or []),
            ))

    # Chain relationships
    spec.chain_relationships = list(fm_data.get("chain_relationships", []) or [])

    # Oversight rules block (workflow-level extensions per Reference §11)
    oversight_data = fm_data.get("oversight")
    if isinstance(oversight_data, dict):
        rules = WorkflowOversightRules()

        for r in oversight_data.get("chain_propagation_rules", []) or []:
            if isinstance(r, dict):
                rules.chain_propagation_rules.append(ChainPropagationRule(
                    source=str(r.get("source", "")),
                    dependent=str(r.get("dependent", "")),
                    action=str(r.get("action", "")),
                    condition=str(r.get("condition", "")),
                ))

        for r in oversight_data.get("off_dependency_rules", []) or []:
            if isinstance(r, dict):
                rules.off_dependency_rules.append(OFFDependencyRule(
                    off_id=str(r.get("off_id", "")),
                    sections_required=list(r.get("sections_required", []) or []),
                    stale_threshold_days=int(r.get("stale_threshold_days", 0) or 0),
                ))

        for r in oversight_data.get("cadence_coordination", []) or []:
            if isinstance(r, dict):
                rules.cadence_coordination.append(CadenceCoordination(
                    sequence=list(r.get("sequence", []) or []),
                    reason=str(r.get("reason", "")),
                ))

        rules.escalation_overrides = dict(oversight_data.get("escalation_overrides", {}) or {})
        spec.oversight = rules

    return spec


# ---------- Reference integrity check (used by workflow_spec_sweeper) ----------

@dataclass
class ReferenceIntegrityIssue:
    issue_type: str  # "missing_file", "stale_reference", "orphan_section"
    artifact: str  # "pff", "off", "corpus_template", "section"
    identifier: str
    detail: str = ""


def check_reference_integrity(
    spec: ParsedWorkflowSpec,
    corpus_template_sections: Optional[list] = None,
    framework_files_exist: Optional[dict] = None,
) -> list[ReferenceIntegrityIssue]:
    """Validate that workflow spec references resolve.

    Args:
        spec: Parsed workflow spec.
        corpus_template_sections: List of section_ids declared in the corpus
            template. If None, section-level checks are skipped.
        framework_files_exist: Dict mapping framework path -> bool. If None,
            file-existence checks are skipped.

    Returns: List of issues. Empty list = clean.
    """
    issues: list[ReferenceIntegrityIssue] = []

    if framework_files_exist is not None:
        for p in spec.pffs:
            if p.path and not framework_files_exist.get(p.path, True):
                issues.append(ReferenceIntegrityIssue(
                    issue_type="missing_file",
                    artifact="pff",
                    identifier=p.name,
                    detail=f"PFF file not found at {p.path}",
                ))
        for o in spec.offs:
            if o.path and not framework_files_exist.get(o.path, True):
                issues.append(ReferenceIntegrityIssue(
                    issue_type="missing_file",
                    artifact="off",
                    identifier=o.name,
                    detail=f"OFF file not found at {o.path}",
                ))

    if corpus_template_sections is not None:
        section_ids = set(corpus_template_sections)
        for p in spec.pffs:
            if p.writes_to_section and p.writes_to_section not in section_ids:
                issues.append(ReferenceIntegrityIssue(
                    issue_type="stale_reference",
                    artifact="pff",
                    identifier=p.name,
                    detail=f"PFF declares writes_to_section={p.writes_to_section!r}, but section is not in corpus template.",
                ))
        for o in spec.offs:
            for sec in o.reads_from_sections:
                if sec not in section_ids:
                    issues.append(ReferenceIntegrityIssue(
                        issue_type="stale_reference",
                        artifact="off",
                        identifier=o.name,
                        detail=f"OFF reads section {sec!r}, but section is not in corpus template.",
                    ))

        # Orphan sections — declared in template but no PFF writes to them
        sections_with_writers = {p.writes_to_section for p in spec.pffs if p.writes_to_section}
        orphans = section_ids - sections_with_writers
        for orphan in orphans:
            issues.append(ReferenceIntegrityIssue(
                issue_type="orphan_section",
                artifact="section",
                identifier=orphan,
                detail=f"Corpus template declares section {orphan!r}, but no PFF in workflow spec writes to it.",
            ))

    return issues


# ---------- Frontmatter splitting ----------

_FRONTMATTER_PATTERN = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def _split_frontmatter(content: str) -> tuple[str, str]:
    m = _FRONTMATTER_PATTERN.match(content)
    if not m:
        return ("", content)
    return (m.group(1), content[m.end():])


# ---------- CLI smoke test ----------

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python workflow_spec_parser.py <path-to-workflow-spec>")
        sys.exit(1)
    spec = parse_workflow_spec_file(sys.argv[1])
    print(f"Workflow: {spec.workflow_name} (id={spec.workflow_id})")
    print(f"Owner: {spec.owner}")
    print(f"Corpus template: {spec.corpus_template_path}")
    print(f"PFFs: {len(spec.pffs)}")
    for p in spec.pffs:
        print(f"  - {p.name} → section={p.writes_to_section}")
    print(f"OFFs: {len(spec.offs)}")
    for o in spec.offs:
        print(f"  - {o.name} reads {o.reads_from_sections}")
    if spec.oversight:
        print(f"Oversight rules: {len(spec.oversight.chain_propagation_rules)} chain, {len(spec.oversight.off_dependency_rules)} OFF, {len(spec.oversight.cadence_coordination)} cadence")
