#!/usr/bin/env python3
"""Router config_name parameter tests (install Chunk 2b).

Covers the new named-configuration resolution path: when the Router is
called with ``config_name="user-pipeline"`` (or any other configuration
in config/configurations/), slot resolution reads the cell's
primary + fallback[] list rather than walking pipelines[context] →
buckets[bucket_name].

During the Chunk-2b→2d transition these tests asserted the config_name path
resolved to the SAME endpoint as the legacy no-config path. That cutover is now
complete (MSI_CHAIN_FROM_CONFIG): production always supplies a config_name, the
legacy no-config path is vestigial, and the configs are re-baked independently of
the now-stale legacy buckets — so the two paths legitimately diverge. The tests
therefore assert the live invariant instead: the config_name path resolves every
workhorse slot to a usable endpoint.
"""
from __future__ import annotations

import json
import os
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

HERE = Path(__file__).resolve().parent
ORCHESTRATOR = HERE.parent
sys.path.insert(0, str(ORCHESTRATOR))

from router import Router  # noqa: E402


class TestConfigNameEquivalence(unittest.TestCase):
    """The new path returns the same endpoint as the legacy path."""

    @classmethod
    def setUpClass(cls):
        # Uses the real routing-config.json + the seed configurations
        # generated by scripts/migrate-to-configurations.py.
        cls.router = Router()

    def _equivalence(self, slot, gear, context, config_name):
        # Post-cutover (MSI_CHAIN_FROM_CONFIG): the config_name path is the live,
        # authoritative one — production always supplies a config_name. The
        # legacy no-config path is vestigial and no longer guaranteed to agree
        # (configs are re-baked independently of the now-stale legacy buckets),
        # so the original equivalence assertion is obsolete. The meaningful
        # invariant is that the config path resolves every workhorse slot to a
        # usable endpoint.
        ep = self.router.resolve_endpoint(
            slot=slot, gear=gear, context=context, config_name=config_name)
        self.assertIsNotNone(
            ep, f"config path resolved no endpoint for slot={slot} gear={gear} "
                f"context={context} config_name={config_name}")
        self.assertTrue(
            isinstance(ep.get("id"), str) and ep["id"],
            f"config path resolved slot={slot} to a malformed endpoint: {ep!r}")

    def test_interactive_utility_step1_cleanup(self):
        self._equivalence("step1_cleanup", 1, "interactive", "user-pipeline")

    def test_interactive_utility_classification(self):
        self._equivalence("classification", 1, "interactive", "user-pipeline")

    def test_interactive_utility_rag_planner(self):
        self._equivalence("rag_planner", 1, "interactive", "user-pipeline")

    def test_interactive_analysis_gear4_depth(self):
        self._equivalence("depth", 4, "interactive", "user-pipeline")

    def test_interactive_analysis_gear4_breadth(self):
        self._equivalence("breadth", 4, "interactive", "user-pipeline")

    def test_interactive_analysis_gear3_depth(self):
        self._equivalence("depth", 3, "interactive", "user-pipeline")

    def test_agent_utility_step1_cleanup(self):
        self._equivalence("step1_cleanup", 1, "agent", "background-default")

    def test_agent_analysis_gear4_depth(self):
        self._equivalence("depth", 4, "agent", "background-default")

    def test_agent_analysis_gear4_breadth(self):
        self._equivalence("breadth", 4, "agent", "background-default")


class TestConfigNamePostAnalysis(unittest.TestCase):
    """Post-analysis slot resolution via config_name."""

    @classmethod
    def setUpClass(cls):
        cls.router = Router()

    def _equivalence(self, slot, context, config_name):
        # See TestConfigNameEquivalence._equivalence: post-cutover the config
        # path is authoritative; assert it resolves to a usable endpoint rather
        # than equal the vestigial legacy no-config path.
        ep = self.router.resolve_post_analysis_slot(slot, context, config_name=config_name)
        self.assertIsNotNone(
            ep, f"config path resolved no post-analysis endpoint for slot={slot} "
                f"context={context} config_name={config_name}")
        self.assertTrue(
            isinstance(ep.get("id"), str) and ep["id"],
            f"config path resolved post-analysis slot={slot} to a malformed endpoint: {ep!r}")

    def test_interactive_consolidation(self):
        self._equivalence("consolidation", "interactive", "user-pipeline")

    def test_interactive_verification(self):
        self._equivalence("verification", "interactive", "user-pipeline")

    def test_agent_consolidation(self):
        self._equivalence("consolidation", "agent", "background-default")

    def test_agent_verification(self):
        self._equivalence("verification", "agent", "background-default")


class TestConfigNameUtility(unittest.TestCase):
    """Utility slot resolution via config_name."""

    @classmethod
    def setUpClass(cls):
        cls.router = Router()

    def _equivalence(self, slot, context, config_name):
        # See TestConfigNameEquivalence._equivalence: post-cutover the config
        # path is authoritative; assert it resolves to a usable endpoint rather
        # than equal the vestigial legacy no-config path.
        ep = self.router.resolve_utility_slot(slot, context, config_name=config_name)
        self.assertIsNotNone(
            ep, f"config path resolved no utility endpoint for slot={slot} "
                f"context={context} config_name={config_name}")
        self.assertTrue(
            isinstance(ep.get("id"), str) and ep["id"],
            f"config path resolved utility slot={slot} to a malformed endpoint: {ep!r}")

    def test_interactive_step1_cleanup(self):
        self._equivalence("step1_cleanup", "interactive", "user-pipeline")

    def test_interactive_classification(self):
        self._equivalence("classification", "interactive", "user-pipeline")

    def test_interactive_rag_planner(self):
        self._equivalence("rag_planner", "interactive", "user-pipeline")

    def test_agent_step1_cleanup(self):
        self._equivalence("step1_cleanup", "agent", "background-default")


class TestExecuteWithConfigName(unittest.TestCase):
    """execute() with config_name resolves a full gear's assignments to valid
    endpoints. (Post-cutover the config path is authoritative and no longer
    mirrors the vestigial legacy context-based path — see the module docstring.)"""

    @classmethod
    def setUpClass(cls):
        cls.router = Router()

    def _assert_valid_gear4(self, config_name):
        res = self.router.execute(
            requested_gear=4, context="interactive", config_name=config_name)
        self.assertEqual(res.gear, 4)
        ids = {s: ep.get("id") for s, ep in res.assignments_v2.items()}
        self.assertTrue(ids, f"no gear-4 assignments for config_name={config_name}")
        for slot, eid in ids.items():
            self.assertTrue(
                isinstance(eid, str) and eid,
                f"config {config_name} resolved slot={slot} to a malformed id: {eid!r}")

    def test_execute_gear4_interactive_resolves(self):
        self._assert_valid_gear4("user-pipeline")

    def test_execute_gear4_agent_resolves(self):
        self._assert_valid_gear4("background-default")


class TestConfigNameMissing(unittest.TestCase):
    """Missing or invalid config_name returns None gracefully."""

    @classmethod
    def setUpClass(cls):
        cls.router = Router()

    def test_unknown_config_returns_none(self):
        ep = self.router.resolve_endpoint(
            slot="depth", gear=4, context="interactive",
            config_name="this-config-does-not-exist",
        )
        self.assertIsNone(ep)

    def test_unknown_slot_returns_none(self):
        ep = self.router.resolve_endpoint(
            slot="totally-unknown-slot", gear=4, context="interactive",
            config_name="user-pipeline",
        )
        self.assertIsNone(ep)


class TestConfigurationCacheClearsOnReload(unittest.TestCase):
    """reload() must invalidate the configuration cache so file edits
    take effect on the next call."""

    def test_cache_cleared_on_reload(self):
        router = Router()
        # Warm the cache
        router._load_configuration("user-pipeline")
        self.assertIn("user-pipeline", router._configurations)

        # Reload should clear the cache via _build_lookup_tables.
        router.reload()
        self.assertEqual(router._configurations, {})


class TestProjectOwnedConfiguration(unittest.TestCase):
    def test_msi_path_override_and_role_reference(self):
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "msi-model-routing.json"
            path.write_text(json.dumps({
                "roles": {
                    "big1": {"primary": "xiaomi/mimo-v2.5",
                             "fallback": ["deepseek/deepseek-v4-flash"]},
                },
                "cells": {"analysis": {"gear4": {
                    "depth": {"role": "big1"},
                }}},
            }), encoding="utf-8")
            env = {
                "MSI_GEAR4_CONFIG_NAME": "msi-publication",
                "MSI_BACKGROUND_CONFIG_PATH": str(path),
            }
            with mock.patch.dict(os.environ, env):
                router = Router()
                self.assertEqual(
                    router._configuration_path("msi-publication"), path)
                self.assertEqual(
                    router.get_slot_chain("depth", 4, "msi-publication"),
                    ["xiaomi/mimo-v2.5", "deepseek/deepseek-v4-flash"],
                )
                self.assertNotEqual(
                    router._configuration_path("background-default"), path)


class TestVisionCapableLookup(unittest.TestCase):
    """vision_capable_for_endpoint prefers models.json (Chunk 2e)."""

    @classmethod
    def setUpClass(cls):
        cls.router = Router()

    def test_local_model_text_only(self):
        # All local MLX models are text-only per models.json.
        self.assertFalse(self.router.vision_capable_for_endpoint("local-mlx-hermes-4-70b"))
        self.assertFalse(self.router.vision_capable_for_endpoint("local-mlx-kimi-dev-72b"))
        self.assertFalse(self.router.vision_capable_for_endpoint("local-mlx-qwen3.5-4b"))

    def test_unknown_endpoint_defaults_false(self):
        self.assertFalse(self.router.vision_capable_for_endpoint("definitely-not-an-endpoint"))

    def test_lookup_cached(self):
        router = Router()
        # Warm
        router.vision_capable_for_endpoint("local-mlx-hermes-4-70b")
        cache1 = router._vision_lookup_cache
        # Second call returns cached
        router.vision_capable_for_endpoint("local-mlx-kimi-dev-72b")
        cache2 = router._vision_lookup_cache
        self.assertIs(cache1, cache2)

    def test_cache_cleared_on_reload(self):
        router = Router()
        # Warm
        router.vision_capable_for_endpoint("local-mlx-hermes-4-70b")
        self.assertIsNotNone(router._vision_lookup_cache)
        # Reload clears via _build_lookup_tables
        router.reload()
        self.assertIsNone(router._vision_lookup_cache)


if __name__ == "__main__":
    unittest.main()
