#!/usr/bin/env python3
"""Router config_name parameter tests (install Chunk 2b).

Covers the new named-configuration resolution path: when the Router is
called with ``config_name="user-pipeline"`` (or any other configuration
in config/configurations/), slot resolution reads the cell's
primary + fallback[] list rather than walking pipelines[context] →
buckets[bucket_name].

Equivalence between the two paths is the load-bearing property — until
Chunk 2d's cutover, legacy callers without ``config_name`` must keep
working unchanged, and new callers with ``config_name`` must resolve
to the same endpoints they would have under the legacy path.
"""
from __future__ import annotations

import sys
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
ORCHESTRATOR = HERE.parent
sys.path.insert(0, str(ORCHESTRATOR))

from router import Router  # noqa: E402


class TestConfigNameEquivalence(unittest.TestCase):
    """The new path returns the same endpoint as the legacy path."""

    @classmethod
    def setUpClass(cls):
        # Uses the real routing-config.json + the seed configurations
        # generated by scripts/migrate-to-configurations.py.
        cls.router = Router()

    def _equivalence(self, slot, gear, context, config_name):
        legacy = self.router.resolve_endpoint(slot=slot, gear=gear, context=context)
        via_config = self.router.resolve_endpoint(
            slot=slot, gear=gear, context=context, config_name=config_name
        )
        legacy_id = legacy["id"] if legacy else None
        config_id = via_config["id"] if via_config else None
        self.assertEqual(
            legacy_id, config_id,
            f"Mismatch for slot={slot} gear={gear} context={context} "
            f"config_name={config_name}: legacy={legacy_id!r}, "
            f"via_config={config_id!r}",
        )

    def test_interactive_utility_step1_cleanup(self):
        self._equivalence("step1_cleanup", 1, "interactive", "user-pipeline")

    def test_interactive_utility_classification(self):
        self._equivalence("classification", 1, "interactive", "user-pipeline")

    def test_interactive_utility_rag_planner(self):
        self._equivalence("rag_planner", 1, "interactive", "user-pipeline")

    def test_interactive_analysis_gear4_depth(self):
        self._equivalence("depth", 4, "interactive", "user-pipeline")

    def test_interactive_analysis_gear4_breadth(self):
        self._equivalence("breadth", 4, "interactive", "user-pipeline")

    def test_interactive_analysis_gear3_depth(self):
        self._equivalence("depth", 3, "interactive", "user-pipeline")

    def test_agent_utility_step1_cleanup(self):
        self._equivalence("step1_cleanup", 1, "agent", "background-default")

    def test_agent_analysis_gear4_depth(self):
        self._equivalence("depth", 4, "agent", "background-default")

    def test_agent_analysis_gear4_breadth(self):
        self._equivalence("breadth", 4, "agent", "background-default")


class TestConfigNamePostAnalysis(unittest.TestCase):
    """Post-analysis slot resolution via config_name."""

    @classmethod
    def setUpClass(cls):
        cls.router = Router()

    def _equivalence(self, slot, context, config_name):
        legacy = self.router.resolve_post_analysis_slot(slot, context)
        via_config = self.router.resolve_post_analysis_slot(
            slot, context, config_name=config_name
        )
        legacy_id = legacy["id"] if legacy else None
        config_id = via_config["id"] if via_config else None
        self.assertEqual(
            legacy_id, config_id,
            f"Mismatch for slot={slot} context={context} "
            f"config_name={config_name}: legacy={legacy_id!r}, "
            f"via_config={config_id!r}",
        )

    def test_interactive_consolidation(self):
        self._equivalence("consolidation", "interactive", "user-pipeline")

    def test_interactive_verification(self):
        self._equivalence("verification", "interactive", "user-pipeline")

    def test_agent_consolidation(self):
        self._equivalence("consolidation", "agent", "background-default")

    def test_agent_verification(self):
        self._equivalence("verification", "agent", "background-default")


class TestConfigNameUtility(unittest.TestCase):
    """Utility slot resolution via config_name."""

    @classmethod
    def setUpClass(cls):
        cls.router = Router()

    def _equivalence(self, slot, context, config_name):
        legacy = self.router.resolve_utility_slot(slot, context)
        via_config = self.router.resolve_utility_slot(
            slot, context, config_name=config_name
        )
        legacy_id = legacy["id"] if legacy else None
        config_id = via_config["id"] if via_config else None
        self.assertEqual(
            legacy_id, config_id,
            f"Mismatch for slot={slot} context={context} "
            f"config_name={config_name}: legacy={legacy_id!r}, "
            f"via_config={config_id!r}",
        )

    def test_interactive_step1_cleanup(self):
        self._equivalence("step1_cleanup", "interactive", "user-pipeline")

    def test_interactive_classification(self):
        self._equivalence("classification", "interactive", "user-pipeline")

    def test_interactive_rag_planner(self):
        self._equivalence("rag_planner", "interactive", "user-pipeline")

    def test_agent_step1_cleanup(self):
        self._equivalence("step1_cleanup", "agent", "background-default")


class TestExecuteWithConfigName(unittest.TestCase):
    """execute() with config_name should resolve a full gear's assignments
    equivalently to the legacy context-based path."""

    @classmethod
    def setUpClass(cls):
        cls.router = Router()

    def test_execute_gear4_interactive_matches(self):
        legacy = self.router.execute(requested_gear=4, context="interactive")
        via_cfg = self.router.execute(
            requested_gear=4, context="interactive", config_name="user-pipeline",
        )
        # Same effective gear and same assignments
        self.assertEqual(legacy.gear, via_cfg.gear)
        legacy_ids = {s: ep.get("id") for s, ep in legacy.assignments_v2.items()}
        via_cfg_ids = {s: ep.get("id") for s, ep in via_cfg.assignments_v2.items()}
        self.assertEqual(legacy_ids, via_cfg_ids)

    def test_execute_gear4_agent_matches(self):
        legacy = self.router.execute(requested_gear=4, context="agent")
        via_cfg = self.router.execute(
            requested_gear=4, context="agent", config_name="background-default",
        )
        self.assertEqual(legacy.gear, via_cfg.gear)
        legacy_ids = {s: ep.get("id") for s, ep in legacy.assignments_v2.items()}
        via_cfg_ids = {s: ep.get("id") for s, ep in via_cfg.assignments_v2.items()}
        self.assertEqual(legacy_ids, via_cfg_ids)


class TestConfigNameMissing(unittest.TestCase):
    """Missing or invalid config_name returns None gracefully."""

    @classmethod
    def setUpClass(cls):
        cls.router = Router()

    def test_unknown_config_returns_none(self):
        ep = self.router.resolve_endpoint(
            slot="depth", gear=4, context="interactive",
            config_name="this-config-does-not-exist",
        )
        self.assertIsNone(ep)

    def test_unknown_slot_returns_none(self):
        ep = self.router.resolve_endpoint(
            slot="totally-unknown-slot", gear=4, context="interactive",
            config_name="user-pipeline",
        )
        self.assertIsNone(ep)


class TestConfigurationCacheClearsOnReload(unittest.TestCase):
    """reload() must invalidate the configuration cache so file edits
    take effect on the next call."""

    def test_cache_cleared_on_reload(self):
        router = Router()
        # Warm the cache
        router._load_configuration("user-pipeline")
        self.assertIn("user-pipeline", router._configurations)

        # Reload should clear the cache via _build_lookup_tables.
        router.reload()
        self.assertEqual(router._configurations, {})


if __name__ == "__main__":
    unittest.main()
