"""Tests for the Engram Cleaning Framework — resolver parsing and detection log filter.

Covers two bugs surfaced 2026-05-09:
- Resolver was reading the resolution marker from the heading line instead of
  the canonical `**Resolution:** [marker]` line.
- Detection wasn't filtering previously-resolved pairs from the log, causing
  the same pairs to resurface every run.
"""

from __future__ import annotations

import os
import sys
import unittest

# Make `orchestrator.historical.*` importable when run from the repo root
sys.path.insert(0, os.path.expanduser("~/ora"))

from orchestrator.historical.run_engram_cleaning_resolver import (
    parse_queue,
    _rebuild_queue_keeping_pending,
)
from orchestrator.historical.run_engram_cleaning_detection import (
    _parse_log_for_pair_keys,
    detect_bidirectional,
)


def _queue_section(heading_marker: str, resolution_marker: str,
                   source_slug: str = "source-test",
                   target_slug: str = "target-test") -> str:
    """Build a single pair section in the queue's canonical format."""
    return (
        f"## [{heading_marker}] Some heading text...\n"
        "\n"
        f"- **Source:** [[{source_slug}]] (modified 2026-01-01, provenance: user)\n"
        f"  *Source claim H1*\n"
        f"- **Target:** [[{target_slug}]] (modified 2026-01-02, provenance: ai-derived)\n"
        f"  *Target claim H1*\n"
        "- **Confidence:** high\n"
        "- **Strategy:** bidirectional\n"
        "\n"
        f"**Resolution:** [{resolution_marker}]\n"
        "\n"
        "---\n"
    )


def _queue_text(*sections: str) -> str:
    preamble = (
        "---\nnexus:\n  - ora\ntype: working\n---\n\n"
        "# Engram Cleaning Queue — test\n\n"
        "*Generated by test fixture.*\n\n"
        "---\n\n"
    )
    return preamble + "\n".join(sections)


class TestResolverReadsResolutionLine(unittest.TestCase):
    """The canonical marker is the `**Resolution:**` line, not the heading."""

    def test_resolution_overrides_pending_heading(self):
        """User edited only the Resolution line; heading still says [pending]."""
        text = _queue_text(_queue_section(
            heading_marker="pending", resolution_marker="skip"
        ))
        pairs = parse_queue(text)
        self.assertEqual(len(pairs), 1)
        self.assertEqual(pairs[0]["resolution"], "skip")

    def test_resolution_with_compound_marker(self):
        text = _queue_text(_queue_section(
            heading_marker="pending",
            resolution_marker="changed-mind:source-supersedes-target",
        ))
        pairs = parse_queue(text)
        self.assertEqual(pairs[0]["resolution"], "changed-mind:source-supersedes-target")

    def test_synced_heading_and_resolution(self):
        """When both have the same marker, parser reads consistently."""
        text = _queue_text(_queue_section(
            heading_marker="wrong:source", resolution_marker="wrong:source"
        ))
        pairs = parse_queue(text)
        self.assertEqual(pairs[0]["resolution"], "wrong:source")

    def test_extracts_slugs_and_h1s(self):
        text = _queue_text(_queue_section(
            heading_marker="pending", resolution_marker="skip",
            source_slug="alpha", target_slug="beta",
        ))
        pairs = parse_queue(text)
        self.assertEqual(pairs[0]["source_slug"], "alpha")
        self.assertEqual(pairs[0]["target_slug"], "beta")
        self.assertEqual(pairs[0]["source_h1"], "Source claim H1")
        self.assertEqual(pairs[0]["target_h1"], "Target claim H1")

    def test_multiple_pairs(self):
        text = _queue_text(
            _queue_section("pending", "skip", "a", "b"),
            _queue_section("pending", "wrong:target", "c", "d"),
            _queue_section("pending", "pending", "e", "f"),
        )
        pairs = parse_queue(text)
        self.assertEqual(len(pairs), 3)
        self.assertEqual(pairs[0]["resolution"], "skip")
        self.assertEqual(pairs[1]["resolution"], "wrong:target")
        self.assertEqual(pairs[2]["resolution"], "pending")


class TestQueueRebuild(unittest.TestCase):
    """Queue rebuild keeps only sections whose Resolution line is [pending]."""

    def test_keeps_only_pending(self):
        text = _queue_text(
            _queue_section("pending", "skip", "a", "b"),
            _queue_section("pending", "pending", "c", "d"),
            _queue_section("pending", "wrong:source", "e", "f"),
        )
        rebuilt = _rebuild_queue_keeping_pending(text)
        # The section with [c]-[d] (Resolution: pending) should remain
        self.assertIn("[[c]]", rebuilt)
        self.assertIn("[[d]]", rebuilt)
        # The other two should be removed
        self.assertNotIn("[[a]]", rebuilt)
        self.assertNotIn("[[b]]", rebuilt)
        self.assertNotIn("[[e]]", rebuilt)
        self.assertNotIn("[[f]]", rebuilt)

    def test_resolution_line_is_canonical_for_rebuild(self):
        """Heading [pending] but Resolution [skip] should still be removed."""
        text = _queue_text(_queue_section(
            heading_marker="pending", resolution_marker="skip",
            source_slug="x", target_slug="y",
        ))
        rebuilt = _rebuild_queue_keeping_pending(text)
        self.assertNotIn("[[x]]", rebuilt)
        self.assertNotIn("[[y]]", rebuilt)

    def test_all_pending_returns_unchanged_pairs(self):
        text = _queue_text(
            _queue_section("pending", "pending", "a", "b"),
            _queue_section("pending", "pending", "c", "d"),
        )
        rebuilt = _rebuild_queue_keeping_pending(text)
        self.assertIn("[[a]]", rebuilt)
        self.assertIn("[[c]]", rebuilt)


class TestLogPairKeyParser(unittest.TestCase):
    """The log-parser produces canonical (sorted) source-target tuples."""

    def test_extracts_pair_from_log_entry(self):
        log = (
            "## 2026-05-09 16:24 — skip\n\n"
            "- **Source:** [[slug-alpha]]\n"
            "- **Target:** [[slug-beta]]\n"
            "- **Files mutated:** (none)\n\n"
            "---\n"
        )
        pairs = _parse_log_for_pair_keys(log)
        # Canonical (sorted) tuple
        self.assertIn(("slug-alpha", "slug-beta"), pairs)
        self.assertEqual(len(pairs), 1)

    def test_canonical_sorting(self):
        """Source/target order in the log doesn't matter — pair key is sorted."""
        log_one = (
            "- **Source:** [[zebra]]\n- **Target:** [[apple]]\n"
        )
        log_two = (
            "- **Source:** [[apple]]\n- **Target:** [[zebra]]\n"
        )
        self.assertEqual(
            _parse_log_for_pair_keys(log_one),
            _parse_log_for_pair_keys(log_two),
        )

    def test_multiple_log_entries(self):
        log = (
            "- **Source:** [[a]]\n- **Target:** [[b]]\n\n"
            "- **Source:** [[c]]\n- **Target:** [[d]]\n\n"
            "- **Source:** [[e]]\n- **Target:** [[f]]\n"
        )
        pairs = _parse_log_for_pair_keys(log)
        self.assertEqual(len(pairs), 3)
        self.assertEqual(pairs, {("a", "b"), ("c", "d"), ("e", "f")})

    def test_empty_log(self):
        self.assertEqual(_parse_log_for_pair_keys(""), set())


class TestDetectionFiltersResolved(unittest.TestCase):
    """detect_bidirectional skips pairs whose canonical key is in resolved_set."""

    def setUp(self):
        # Build a fake engram index — two engrams that contradict each other.
        self.by_slug = {
            "alpha": {
                "slug": "alpha",
                "h1": "Alpha claim",
                "filename": "alpha.md",
                "path": "/fake/alpha.md",
                "frontmatter": {"tags": []},
            },
            "beta": {
                "slug": "beta",
                "h1": "Beta claim",
                "filename": "beta.md",
                "path": "/fake/beta.md",
                "frontmatter": {"tags": []},
            },
        }
        self.by_h1 = {
            "Alpha claim": self.by_slug["alpha"],
            "Beta claim": self.by_slug["beta"],
        }

    def test_resolved_pair_is_filtered(self):
        """When (alpha, beta) is in resolved_set, detection skips it."""
        # Stub the sqlite call by patching the module-level GRAPH_DB.
        # Easier path: mock the connection inline.
        import unittest.mock as mock
        from orchestrator.historical import run_engram_cleaning_detection as det

        # Edges: alpha contradicts beta-claim AND beta contradicts alpha-claim
        edges = [("alpha", "Beta claim"), ("beta", "Alpha claim")]

        class FakeCursor:
            def execute(self, *_args, **_kw):
                pass

            def fetchall(self):
                return edges

        class FakeConn:
            def cursor(self):
                return FakeCursor()

            def close(self):
                pass

        with mock.patch.object(det.sqlite3, "connect", return_value=FakeConn()):
            # Without filter: pair surfaces
            unfiltered = detect_bidirectional(
                self.by_slug, self.by_h1, limit=10, resolved_set=set()
            )
            self.assertEqual(len(unfiltered), 1)

            # With filter on canonical (alpha, beta): pair is skipped
            filtered = detect_bidirectional(
                self.by_slug, self.by_h1, limit=10,
                resolved_set={("alpha", "beta")},
            )
            self.assertEqual(len(filtered), 0)

    def test_resolved_set_default_is_empty(self):
        """Backward compatibility — old callers without resolved_set still work."""
        import unittest.mock as mock
        from orchestrator.historical import run_engram_cleaning_detection as det

        edges = [("alpha", "Beta claim"), ("beta", "Alpha claim")]

        class FakeCursor:
            def execute(self, *_args, **_kw):
                pass

            def fetchall(self):
                return edges

        class FakeConn:
            def cursor(self):
                return FakeCursor()

            def close(self):
                pass

        with mock.patch.object(det.sqlite3, "connect", return_value=FakeConn()):
            pairs = detect_bidirectional(self.by_slug, self.by_h1, limit=10)
            self.assertEqual(len(pairs), 1)


if __name__ == "__main__":
    unittest.main()
