#!/usr/bin/env bash
# vault-derive-sync.sh — route-authoritative vault -> sites reconcile.
#
# An exact canonical-source commit event fetches vault origin/main into a
# dedicated disposable worktree, validates one complete publication plan, and
# derives every explicitly routed Markdown source into the app, MSI, and
# foundation site worktrees. Any invalid plan refuses all writes, staging, and
# pushes; a partial corpus is never published.
#
# It writes into dedicated git WORKTREES of the working repos (detached on
# origin/main), so it never disturbs the working tree the user edits in sessions
# and never re-downloads the repos. The derive script + deps come from the
# working repo (which has node_modules); the worktrees are pure output + push
# targets.
#
#   vault-derive-sync.sh            # dry run: derive + show what WOULD change
#   vault-derive-sync.sh --push     # derive + commit + push (event pipeline)
set -uo pipefail

export PATH="/Users/oracle/.local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

WORK_VAULT="${VAULT_REPO:-${VAULT_DIR:-$HOME/Documents/vault}}"
WORK_ORA="${ORA_WORKDIR:-$HOME/sites/ora-ai-app}"
WORK_MSI="${MSI_WORKDIR:-$HOME/sites/mainstreetindependent}"
WORK_ORG="${ORG_WORKDIR:-$HOME/sites/ora-ai-org}"
SYNC_ROOT="$HOME/sites/.vault-sync"
VAULT_WT="$SYNC_ROOT/vault"
ORA_WT="$SYNC_ROOT/ora"
MSI_WT="$SYNC_ROOT/msi"
ORG_WT="$SYNC_ROOT/org"
LOG="$SYNC_ROOT/vault-derive-sync.log"
LOCKDIR="$SYNC_ROOT/.lock.d"
DERIVE="$WORK_ORA/scripts/derive-explainer.mjs"

PUSH=0; [[ "${1:-}" == "--push" ]] && PUSH=1

mkdir -p "$SYNC_ROOT"
exec >>"$LOG" 2>&1

# Single-instance lock (macOS has no flock). Clear a stale lock (>30 min).
[[ -d "$LOCKDIR" ]] && [[ -n "$(find "$LOCKDIR" -maxdepth 0 -mmin +30 2>/dev/null)" ]] && rmdir "$LOCKDIR" 2>/dev/null
if ! mkdir "$LOCKDIR" 2>/dev/null; then echo "$(date -u +%FT%TZ) another run in progress; skip"; exit 0; fi
trap 'rmdir "$LOCKDIR" 2>/dev/null' EXIT

echo "===== $(date -u +%FT%TZ) vault-derive-sync start (push=$PUSH) ====="

# Bring a worktree to a clean, detached origin/main (create it if absent). The
# worktree shares the working repo's object store — no download. Disposable:
# safe to hard-reset because nothing here is ever hand-edited.
prep() {
  local work="$1" wt="$2"
  git -C "$work" fetch -q origin || return 1
  if [[ ! -d "$wt/.git" && ! -f "$wt/.git" ]]; then
    echo "creating worktree $wt"
    git -C "$work" worktree prune
    git -C "$work" worktree add -q --detach "$wt" origin/main || return 1
  fi
  git -C "$wt" checkout -q --detach origin/main || return 1
  git -C "$wt" reset -q --hard origin/main || return 1
  git -C "$wt" clean -fdq || true
}
prep "$WORK_VAULT" "$VAULT_WT" || { echo "vault worktree prep failed"; exit 1; }
prep "$WORK_ORA" "$ORA_WT" || { echo "ora worktree prep failed"; exit 1; }
prep "$WORK_MSI" "$MSI_WT" || { echo "msi worktree prep failed"; exit 1; }
prep "$WORK_ORG" "$ORG_WT" || { echo "org worktree prep failed"; exit 1; }

# The generator scans Projects/Ora and Projects/MSI and builds the whole plan in
# memory before the first write. Script + js-yaml come from the working app repo;
# outputs go only to the disposable target worktrees.
if ! VAULT_DIR="$VAULT_WT" ORA_DIR="$ORA_WT" MSI_DIR="$MSI_WT" ORG_DIR="$ORG_WT" \
  node "$DERIVE" --write; then
  echo "canonical route derive failed; refusing to stage or push"
  exit 1
fi
if ! VAULT_DIR="$VAULT_WT" ORA_DIR="$ORA_WT" MSI_DIR="$MSI_WT" ORG_DIR="$ORG_WT" \
  node "$WORK_ORA/scripts/assert-papers-derived.mjs" --prune; then
  echo "derived parity/prune failed; refusing to stage or push"
  exit 1
fi

# Stage only the derived content/public paths, then commit+push if anything moved.
sync_repo() {
  local name="$1" wt="$2"; shift 2
  git -C "$wt" add -- "$@" 2>/dev/null
  if git -C "$wt" diff --cached --quiet; then echo "$name: no changes"; return 0; fi
  local n; n=$(git -C "$wt" diff --cached --name-only | wc -l | tr -d ' ')
  echo "$name: $n changed file(s):"
  git -C "$wt" diff --cached --name-only | sed 's/^/    /' | head -60
  if [[ "$PUSH" == "1" ]]; then
    git -C "$wt" -c user.name='vault-sync-bot' -c user.email='golfplan18@gmail.com' \
      commit -q -m "chore(content): auto-sync derived pages from vault ($n files)" \
      -m "Generated by vault-derive-sync.sh from explicit canonical YAML routes. Do not hand-edit marked derived files." \
      || return 1
    if git -C "$wt" push -q origin HEAD:main; then
      echo "$name: pushed $n files"
    else
      echo "$name: PUSH FAILED; exact event remains failed for explicit retry"
      return 1
    fi
  else
    echo "$name: DRY-RUN (pass --push to commit); unstaging"
    git -C "$wt" reset -q
  fi
}

sync_failed=0
sync_repo "ora" "$ORA_WT" src/content/modes src/content/lenses src/content/visual-outputs src/content/papers src/content/analytical-frameworks src/content/functional-frameworks public/papers public/downloads || sync_failed=1
sync_repo "msi" "$MSI_WT" src/content/mode-explainers src/content/lens-explainers src/content/papers src/content/methodology-docs src/content/propaganda-docs src/content/mind-papers src/content/voice-frameworks src/content/mindspecs src/content/dossiers public/papers public/downloads || sync_failed=1
sync_repo "org" "$ORG_WT" src/content/frameworks-canonical || sync_failed=1
if [[ "$sync_failed" != "0" ]]; then
  echo "one or more derived targets failed"
  exit 1
fi

echo "===== $(date -u +%FT%TZ) vault-derive-sync done ====="
