#!/bin/bash
# compile-rag-manifest.sh — Compiles the canonical RAG manifest into a token-optimized operational version.
# Only runs when canonical modification date is newer than compiled modification date.

set -uo pipefail

ORA_DIR="${HOME}/ora"
CONFIG_DIR="${ORA_DIR}/config"
CANONICAL="${CONFIG_DIR}/rag-manifest.md"
COMPILED="${CONFIG_DIR}/rag-manifest-compiled.md"

# Check if recompilation is needed
if [ -f "$COMPILED" ]; then
    canonical_mod=$(stat -f %m "$CANONICAL" 2>/dev/null || stat -c %Y "$CANONICAL")
    compiled_mod=$(stat -f %m "$COMPILED" 2>/dev/null || stat -c %Y "$COMPILED")
    if [ "$canonical_mod" -le "$compiled_mod" ]; then
        echo "Compiled manifest is up to date. No recompilation needed."
        exit 0
    fi
fi

echo "Compiling RAG manifest..."

# Build compiled version: strip explanatory text, compress to operational notation
cat > "$COMPILED" << 'HEADER'
# RAG Manifest — Compiled
# Auto-generated by compile-rag-manifest.sh — do not edit manually.
# Source: config/rag-manifest.md

HEADER

# Resource table (compact)
echo "## Resources" >> "$COMPILED"
echo "" >> "$COMPILED"
echo "| ID | Type | Location | Provenance | Token Est |" >> "$COMPILED"
echo "|---|---|---|---|---|" >> "$COMPILED"
echo "| conversation-history | vector-search | chromadb/conversations | moderate | 500-2000 |" >> "$COMPILED"
echo "| vault-knowledge | vector-search | chromadb/knowledge | type-derived | 1000-4000 |" >> "$COMPILED"
echo "| approved-sources | url-fetch | config/approved-sources.md | tiered A/B/C | 2000-6000 |" >> "$COMPILED"
echo "| web-search | open-internet | tools/web_search.py | lowest | 1000-3000 |" >> "$COMPILED"
echo "| modes-directory | direct-file | modes/ | system | 2000-4000 |" >> "$COMPILED"
echo "| framework-library | direct-file+vector | frameworks/ | system | 3000-8000 |" >> "$COMPILED"
echo "| file-reference | direct-file | vault/ or ora/ | inherited | variable |" >> "$COMPILED"
echo "" >> "$COMPILED"

# Include approved sources (compact)
echo "## Approved Sources" >> "$COMPILED"
echo "" >> "$COMPILED"
if [ -f "${CONFIG_DIR}/approved-sources.md" ]; then
    grep "^|" "${CONFIG_DIR}/approved-sources.md" | grep -v "^|---" | grep -v "^| Source" >> "$COMPILED" || true
fi
echo "" >> "$COMPILED"

# Include excluded sources (compact)
echo "## Excluded Sources" >> "$COMPILED"
echo "" >> "$COMPILED"
if [ -f "${CONFIG_DIR}/excluded-sources.md" ]; then
    excluded_count=$(grep "^|" "${CONFIG_DIR}/excluded-sources.md" | grep -v "^|---" | grep -v "^| Domain" | grep -v "(none" | wc -l | tr -d ' ')
    echo "Count: ${excluded_count}" >> "$COMPILED"
    if [ "$excluded_count" -gt 0 ]; then
        grep "^|" "${CONFIG_DIR}/excluded-sources.md" | grep -v "^|---" | grep -v "^| Domain" | grep -v "(none" >> "$COMPILED" || true
    fi
fi
echo "" >> "$COMPILED"

# Include modes index (compact)
echo "## Modes" >> "$COMPILED"
echo "" >> "$COMPILED"
if [ -f "${CONFIG_DIR}/modes-index.md" ]; then
    grep "^|" "${CONFIG_DIR}/modes-index.md" | grep -v "^|---" >> "$COMPILED" || true
fi
echo "" >> "$COMPILED"

# Include framework library index (compact)
echo "## Frameworks" >> "$COMPILED"
echo "" >> "$COMPILED"
if [ -f "${CONFIG_DIR}/framework-library-index.md" ]; then
    grep "^|" "${CONFIG_DIR}/framework-library-index.md" | grep -v "^|---" >> "$COMPILED" || true
fi

# Token count check
token_estimate=$(wc -w < "$COMPILED")
echo "" >> "$COMPILED"
echo "# Estimated tokens: ~${token_estimate}" >> "$COMPILED"

echo "Compiled: ${COMPILED} (~${token_estimate} words)"

if [ "$token_estimate" -gt 4000 ]; then
    echo "WARNING: Compiled manifest exceeds 4000 word estimate. Consider trimming."
fi
