#!/bin/bash
# generate-indexes.sh — Regenerates framework-library-index.md and modes-index.md
# Run during maintenance cycle or after adding/modifying frameworks or modes.

set -uo pipefail

ORA_DIR="${HOME}/ora"
CONFIG_DIR="${ORA_DIR}/config"

# --- Framework Library Index ---
FRAMEWORK_INDEX="${CONFIG_DIR}/framework-library-index.md"
echo "# Framework Library Index" > "$FRAMEWORK_INDEX"
echo "" >> "$FRAMEWORK_INDEX"
echo "*Auto-generated by generate-indexes.sh — do not edit manually.*" >> "$FRAMEWORK_INDEX"
echo "" >> "$FRAMEWORK_INDEX"
echo "| File | Path | Description |" >> "$FRAMEWORK_INDEX"
echo "|---|---|---|" >> "$FRAMEWORK_INDEX"

for dir in "${ORA_DIR}/frameworks/book" "${ORA_DIR}/frameworks/user" "${ORA_DIR}/frameworks/personal"; do
    if [ -d "$dir" ]; then
        for f in "$dir"/*.md; do
            [ -f "$f" ] || continue
            filename=$(basename "$f")
            # Extract first non-empty, non-heading, non-frontmatter line as description
            desc=$(awk '/^---$/{fm++; next} fm==1{next} /^#/{next} /^$/{next} {print; exit}' "$f" | head -c 120)
            echo "| ${filename} | ${f} | ${desc} |" >> "$FRAMEWORK_INDEX"
        done
    fi
done

echo "Generated: ${FRAMEWORK_INDEX}"

# --- Modes Directory Index ---
MODES_INDEX="${CONFIG_DIR}/modes-index.md"
echo "# Modes Directory Index" > "$MODES_INDEX"
echo "" >> "$MODES_INDEX"
echo "*Auto-generated by generate-indexes.sh — do not edit manually.*" >> "$MODES_INDEX"
echo "" >> "$MODES_INDEX"
echo "| Mode | File | Default Gear | Trigger Summary |" >> "$MODES_INDEX"
echo "|---|---|---|---|" >> "$MODES_INDEX"

for f in "${ORA_DIR}/modes/"*.md; do
    [ -f "$f" ] || continue
    filename=$(basename "$f")
    mode_name=$(basename "$f" .md | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1')
    # Extract default gear
    gear=$(grep -A2 "## DEFAULT GEAR" "$f" | grep -oE "Gear [0-9]" | head -1)
    [ -z "$gear" ] && gear="—"
    # Extract first positive trigger line (truncated)
    trigger=$(grep -A1 "Positive triggers:" "$f" | tail -1 | head -c 80)
    [ -z "$trigger" ] && trigger=$(awk '/Positive triggers:/{print; exit}' "$f" | sed 's/Positive triggers: //' | head -c 80)
    echo "| ${mode_name} | ${filename} | ${gear} | ${trigger} |" >> "$MODES_INDEX"
done

echo "Generated: ${MODES_INDEX}"
