#!/bin/bash
# generate-indexes.sh — Regenerates framework-library-index.md and modes-index.md
# Run during maintenance cycle or after adding/modifying frameworks or modes.

set -uo pipefail

# Resolve the workspace the way start.sh and run-ora-server.sh do: an explicit
# ORA_HOME wins, otherwise this script belongs to the checkout it lives in. The
# old "${HOME}/ora" pin meant a clone anywhere else read and rewrote a
# completely unrelated tree — or nothing at all, on a machine with no ~/ora.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
ORA_DIR="${ORA_HOME:-$(cd -- "${SCRIPT_DIR}/.." && pwd -P)}"
if [ ! -d "$ORA_DIR" ]; then
    echo "ERROR: ORA_HOME is not a directory: $ORA_DIR" >&2
    exit 1
fi
ORA_DIR="$(cd -- "$ORA_DIR" && pwd -P)"
CONFIG_DIR="${ORA_DIR}/config"

# --- Framework Library Index ---
FRAMEWORK_INDEX="${CONFIG_DIR}/framework-library-index.md"
echo "# Framework Library Index" > "$FRAMEWORK_INDEX"
echo "" >> "$FRAMEWORK_INDEX"
echo "*Auto-generated by generate-indexes.sh — do not edit manually.*" >> "$FRAMEWORK_INDEX"
echo "" >> "$FRAMEWORK_INDEX"
echo "| File | Path (relative to the Ora workspace root) | Description |" >> "$FRAMEWORK_INDEX"
echo "|---|---|---|" >> "$FRAMEWORK_INDEX"

for dir in "${ORA_DIR}/frameworks/book" "${ORA_DIR}/frameworks/user" "${ORA_DIR}/frameworks/personal"; do
    if [ -d "$dir" ]; then
        for f in "$dir"/*.md; do
            [ -f "$f" ] || continue
            filename=$(basename "$f")
            # Workspace-relative, never absolute: this table is read into a
            # model's context window and ships to every clone, so the
            # packager's own home directory in it is both wrong and useless
            # to the reader.
            relpath="${f#"${ORA_DIR}"/}"
            # Extract first non-empty, non-heading, non-frontmatter line as description
            desc=$(awk '/^---$/{fm++; next} fm==1{next} /^#/{next} /^$/{next} {print; exit}' "$f" | head -c 120)
            echo "| ${filename} | ${relpath} | ${desc} |" >> "$FRAMEWORK_INDEX"
        done
    fi
done

echo "Generated: ${FRAMEWORK_INDEX}"

# --- Modes Directory Index ---
MODES_INDEX="${CONFIG_DIR}/modes-index.md"
echo "# Modes Directory Index" > "$MODES_INDEX"
echo "" >> "$MODES_INDEX"
echo "*Auto-generated by generate-indexes.sh — do not edit manually.*" >> "$MODES_INDEX"
echo "" >> "$MODES_INDEX"
echo "| Mode | File | Default Gear | Trigger Summary |" >> "$MODES_INDEX"
echo "|---|---|---|---|" >> "$MODES_INDEX"

for f in "${ORA_DIR}/modes/"*.md; do
    [ -f "$f" ] || continue
    filename=$(basename "$f")
    mode_name=$(basename "$f" .md | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1')
    # Extract default gear
    gear=$(grep -A2 "## DEFAULT GEAR" "$f" | grep -oE "Gear [0-9]" | head -1)
    [ -z "$gear" ] && gear="—"
    # Extract the trigger phrases from the mode file's YAML block. The old
    # "Positive triggers:" line disappeared with the flat-H2 mode template, so
    # this column silently generated empty for every mode. The template now
    # declares triggers as a `trigger_conditions:` key holding
    # `prompt_shape_signals:` entries; a couple of utility modes put a plain
    # list directly under `trigger_conditions:` instead, so fall back to that.
    # Entries are joined whole, up to the 80-character column budget.
    trigger=$(awk '
        /^trigger_conditions:/ { in_tc = 1; next }
        in_tc && /^[^ \t#]/    { in_tc = 0; in_shape = 0 }
        in_tc && /^  [A-Za-z_]+:/ {
            in_shape = ($0 ~ /^  prompt_shape_signals:/) ? 1 : 0
            next
        }
        in_tc && in_shape && /^    - / { shape[++ns] = trim($0); next }
        in_tc && !in_shape && /^  - / { plain[++np] = trim($0); next }
        function trim(line) {
            sub(/^[ \t]*-[ \t]*/, "", line)
            gsub(/\|/, "\\|", line)
            return line
        }
        END {
            if (ns > 0) { n = ns; for (i = 1; i <= n; i++) item[i] = shape[i] }
            else        { n = np; for (i = 1; i <= n; i++) item[i] = plain[i] }
            out = ""
            for (i = 1; i <= n; i++) {
                candidate = (out == "" ? item[i] : out ", " item[i])
                if (length(candidate) > 80) {
                    if (out == "") out = substr(item[i], 1, 80)
                    break
                }
                out = candidate
            }
            print out
        }
    ' "$f")
    echo "| ${mode_name} | ${filename} | ${gear} | ${trigger} |" >> "$MODES_INDEX"
done

echo "Generated: ${MODES_INDEX}"
