"""Rubric sanity check against the 80-case labelled benchmark.

SCOPE, stated up front: judge_benchmark80_labels.json was generated by an Opus
pairwise judging pass. It is NOT ground truth. This measures whether the A/B
rubric AGREES WITH THE RUBRIC THAT PRODUCED THOSE LABELS. It can catch a
rubric that is wildly off. It cannot validate the +32pp magnitude, because the
yardstick carries the same bias as the instrument.

Imports RUBRIC verbatim from judge_ab.py so this checks the real instrument.
"""
from __future__ import annotations

import json
import os
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

sys.path.insert(0, os.environ["ORA_HOME"])
sys.path.insert(0, str(Path(__file__).parent))

from orchestrator.historical.cleanup_backends import build_client  # noqa: E402
from judge_ab import RUBRIC  # noqa: E402  — the exact rubric under test

MIG = Path("/Users/oracle/engram-work/.migration")
OUT = Path(__file__).parent / "calibration_results.json"
JUDGE_MODEL = os.environ.get("JUDGE_MODEL", "claude-opus-5")
MAX_SRC = 6000


def judge_case(case):
    srcs = case.get("sources") or []
    joined = "\n\n---\n\n".join(str(s) for s in srcs)[:MAX_SRC]
    note = f"TITLE: {case.get('title','')}\n\nBODY:\n{case.get('body','')}"
    user = (f"=== SOURCE MATERIAL ===\n{joined}\n\n"
            f"=== NOTE UNDER JUDGEMENT ===\n{note}\n\nJudge it.")
    c = build_client("api")
    r = c.call(system=RUBRIC, user=user, model=JUDGE_MODEL,
               max_tokens=1200, temperature=None)
    if r.error:
        return {"case_id": case["case_id"], "error": r.error}
    txt = r.text.strip()
    if "```" in txt:
        txt = txt.split("```")[1].lstrip("json").strip()
    try:
        v = json.loads(txt[txt.index("{"):txt.rindex("}") + 1])
    except Exception as e:
        return {"case_id": case["case_id"], "error": f"parse: {e}"}
    return {"case_id": case["case_id"], "mine": v.get("verdict"),
            "worst_problem": v.get("worst_problem", "")}


def main():
    blind = json.loads((MIG / "judge_benchmark80_blind.json").read_text())
    labels = json.loads((MIG / "judge_benchmark80_labels.json").read_text())
    print(f"{len(blind)} blind cases | {len(labels)} labels | rubric from judge_ab.py",
          flush=True)

    with ThreadPoolExecutor(max_workers=6) as ex:
        got = list(ex.map(judge_case, blind))

    rows, errs = [], 0
    for g in got:
        if "error" in g:
            errs += 1
            continue
        lab = labels.get(g["case_id"])
        if lab is None:
            continue
        rows.append({**g, "label": lab, "agree": lab == g["mine"]})

    OUT.write_text(json.dumps(rows, indent=1))
    n = len(rows)
    agree = sum(1 for r in rows if r["agree"])
    # confusion
    tt = sum(1 for r in rows if r["label"] == "SOUND" and r["mine"] == "SOUND")
    tf = sum(1 for r in rows if r["label"] == "SOUND" and r["mine"] == "DEFECT")
    ft = sum(1 for r in rows if r["label"] == "DEFECT" and r["mine"] == "SOUND")
    ff = sum(1 for r in rows if r["label"] == "DEFECT" and r["mine"] == "DEFECT")
    lab_sound = sum(1 for r in rows if r["label"] == "SOUND")
    mine_sound = sum(1 for r in rows if r["mine"] == "SOUND")
    print(f"\nscored {n} cases ({errs} errors)")
    print(f"AGREEMENT WITH THE OPUS-GENERATED LABELS: {agree}/{n} = {100*agree/n:.0f}%")
    print(f"\n                 label SOUND   label DEFECT")
    print(f"  mine SOUND  {tt:10}{ft:14}")
    print(f"  mine DEFECT {tf:10}{ff:14}")
    print(f"\nbase rates: labels {lab_sound}/{n} SOUND ({100*lab_sound/n:.0f}%) | "
          f"mine {mine_sound}/{n} SOUND ({100*mine_sound/n:.0f}%)")
    print(f"strictness: my rubric calls SOUND {'less' if mine_sound < lab_sound else 'more'} often "
          f"({mine_sound - lab_sound:+d} cases)")
    print("->", OUT)


if __name__ == "__main__":
    main()
